name: nf-isoseq
channels:
  - bioconda
  - defaults
dependencies:
  - bioconda::pbbam==1.3.0
  - bioconda::pbccs==4.2.0
  - bioconda::lima==1.11.0
  - bioconda::isoseq3==3.3.0
  - bioconda::gmap
  - bioconda::samtools